name: Trigger Workflow

on:
  push:
    branches:
      - main # Change to your main branch or default branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        uses: actions/http-client@v2
        with:
          method: POST
          url: https://api.github.com/repos/aswinc88/testrepo/dispatches
          headers: |
            Authorization: Bearer ${{ secrets.AUTH_TOKEN }}
            Accept: application/vnd.github.everest-preview+json
            Content-Type: application/json
          data: '{"event_type": "trigger-workflow"}'
