name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_job:
    runs-on: ubuntu-latest
    
    steps:

      - name: Echo parent workflow
        shell: bash
        run: |
            echo "THis is parent repo workflow"
      - name: Trigger child repo workflow           
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" \
        https://api.github.com/repos/aswinc88/testrepo/dispatches \
        -d '{"event_type": "trigger-workflow"}'
