name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_job:
    runs-on: ubuntu-latest
    
    steps:

      - name: Echo parent workflow
        shell: bash
        run: |
            echo "THis is parent repo workflow"
        